name: CI - Project planner

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Hent repository
        uses: actions/checkout@v4

      - name: Sæt Java op
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Byg projekt
        run: mvn -B clean install

      - name: Kør tests
        run: mvn test
